export const CHAMPION_LIST = ["Aatrox", "Ahri", "Akali", "Akshan", "Alistar", "Amumu", "Anivia",
  "Annie", "Aphelios", "Ashe", "Azir", "Bard", "Blitzcrank", "Brand",
  "Braum", "Caitlyn", "Camille", "Cassiopeia", "Cho'Gath", "Chronokeeper",
  "Darius", "Diana", "Dr. Mundo", "Draven", "Ekko", "Elise", "Evelynn",
  "Ezreal", "Fiddlesticks", "Fiora", "Fizz", "Galio", "Gangplank",
  "Garen", "Gnar", "Gragas", "Graves", "Hecarim", "Heimerdinger",
  "Irelia", "Ivern", "Janna", "Jarvan IV", "Jax", "Jayce", "Jhin",
  "Jinx", "K'Sante", "Kai'Sa", "Kalista", "Karma", "Karthus", "Kassadin",
  "Katarina", "Kayle", "Kayn", "Kennen", "Kha'Zix", "Kindred", "Kled",
  "Kog'Maw", "LeBlanc", "Lee Sin", "Leona", "Lissandra", "Lucian",
  "Lulu", "Lux", "Malphite", "Malzahar", "Maokai", "Master Yi", "Milio",
  "Miss Fortune", "Mordekaiser", "Morgana", "Nami", "Nasus", "Nautilus",
  "Neeko", "Nidalee", "Nilah", "Nocturne", "Nunu & Willump", "Olaf",
  "Orianna", "Ornn", "Pantheon", "Poppy", "Pyke", "Qiyana", "Quinn",
  "Rakan", "Rammus", "Rek'Sai", "Renata Glasc", "Renekton", "Rengar",
  "Riven", "Rumble", "Ryze", "Samira", "Sejuani", "Senna", "Seraphine",
  "Sett", "Shaco", "Shen", "Shyvana", "Singed", "Sion", "Sivir",
  "Skarner", "Smolder", "Soraka", "Swain", "Sylas", "Syndra",
  "Tahm Kench", "Taliyah", "Talon", "Taric", "Teemo", "Thresh", "Tristana",
  "Trundle", "Trynda", "Twisted Fate", "Twitch", "Udyr", "Urgot",
  "Varus", "Vayne", "Veigar", "Vel'Koz", "Vex", "Vi", "Viktor", "Vladimir",
  "Volibear", "Wukong", "Xayah", "Xerath", "Xin Zhao", "Yasuo", "Yone",
  "Yorick", "Zac", "Zed", "Ziggs", "Zilean", "Zoe", "Zyra"]